import type { PlantUMLConfig } from "../types/plantumlConfig";

/**
 * PlantUML Diagram Rendering Configuration
 *
 * Controls the build time encoding and client side rendering behavior
 * for converting `plantuml` code blocks in Markdown articles into
 * SVG images generated by a PlantUML server.
 *
 * Supports both light and dark themes, as well as self hosted
 * PlantUML servers.
 *
 * @see https://plantuml.com/theme
 * @see https://plantuml.com/server
 */
export const plantumlConfig: PlantUMLConfig = {
  /**
   * Enable PlantUML rendering.
   *
   * When disabled, `plantuml` code blocks fall back to standard
   * syntax highlighted code blocks handled by Expressive Code.
   */
  enable: true,

  /**
   * PlantUML server URL.
   *
   * A trailing slash is optional and will be normalized automatically.
   *
   * By default, the official public PlantUML server is used.
   * For sensitive or private diagrams, consider deploying your own
   * PlantUML server (for example using the
   * `plantuml/plantuml-server` Docker image) and replace this URL.
   */
  server: "https://www.plantuml.com/plantuml",

  /**
   * Theme name injected into PlantUML source code in light mode.
   *
   * Equivalent to:
   * `!theme <theme-name>`
   *
   * Leave empty to use PlantUML's default appearance.
   */
  lightTheme: "",

  /**
   * Theme name injected into PlantUML source code in dark mode.
   *
   * Equivalent to:
   * `!theme <theme-name>`
   *
   * Leave empty to disable theme injection.
   * The default value uses the built in `cyborg` dark theme.
   */
  darkTheme: "cyborg",
};
